apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-pod
spec:
  containers:
  - name: html-generator
    image: lyteabovenyte/fortune:env
    env:
    - name: INTERVAL
      value: "30"
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - name: web-server
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 84
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
