apiVersion: v1
kind: Pod
metadata:
  name: fortune2s
  labels:
    app: fortune-args
spec:
  containers:
  - name: html-generator
    image: lyteabovenyte/fortune:args
    args: ["3"]
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - name: web-server
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 83
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}