apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod-configmap-volume
spec:
  containers:
  - name: html-generator
    image: lyteabovenyte/fortune:env
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
            name: fortune-config
            key: sleep-interval
  - name: web-server
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: config
      mountPath: /tmp/whole-fortune-config-volume
      readOnly: true
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: fortune-config
