apiVersion: v1
kind: Pod
metadata:
  name: private-image
spec: 
  imagePullSecrets:
  - name: mydockerhub
  containers:
  - name: private-kubia
    image: lyteabovenyte/kubia:v2.0.2
    ports:
    - containerPort: 8080